In [2]:
print('hello world')

hello world


In [3]:
import numpy as np

In [13]:
my_arr = np.array([
    [1,2,3],
    ['foo', 'bar', 9],
    [9, 10, 11]
])

In [14]:
my_arr

array([['1', '2', '3'],
       ['foo', 'bar', '9'],
       ['9', '10', '11']], dtype='<U21')

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [34]:
type(5.)

float

In [35]:
type(5)

int

In [36]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.random.rand(3)

array([0.12092381, 0.74421146, 0.69766682])

In [39]:
np.random.rand(2,4)

array([[0.36761031, 0.84070218, 0.18433673, 0.96529635],
       [0.53215345, 0.3318259 , 0.69005581, 0.70531652]])

In [40]:
np.random.randn(2)

array([-0.2272921 ,  1.41784147])

In [41]:
np.random.randint(0,10,2)

array([5, 1])

In [74]:
a = np.arange(25)
ar = a.reshape(5,5)
print(a)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
rana = np.random.randint(0, 100, 50)
rana

array([62, 78, 48, 45, 92, 60, 28, 51, 36,  4, 97, 96, 68, 67, 41, 59, 61,
       14, 20, 23,  7,  0, 25, 21, 29, 56, 48, 68, 93, 12, 86, 34, 99, 59,
       55, 71,  9, 25,  3, 75, 64, 12, 92, 36, 55, 74, 44, 52, 20, 76])

In [52]:
rana.max()

99

In [53]:
rana.min()

0

In [54]:
rana.argmax()

32

In [55]:
rana[32]

99

In [56]:
rana.argmin()

21

In [57]:
rana[21]

0

In [59]:
rana.shape

(50,)

In [60]:
a.shape

(25,)

In [63]:
ar.shape

(5, 5)

In [64]:
a.dtype

dtype('int64')

In [65]:
ar.dtype

dtype('int64')

In [66]:
np.array(['foo']).dtype

dtype('<U3')

In [67]:
np.array(['fpp', 3]).dtype

dtype('<U3')

In [68]:
np.array([
    [1,2,3],
    ['foo', 'bar', 'baz']
]).dtype

dtype('<U21')

In [71]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
ar[0:2]

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [75]:
ar[0:2] = 5

In [76]:
ar

array([[ 5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
copy = ar.copy()

In [80]:
ar[2,1]

11

In [83]:
ar[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [86]:
ar[2:4,3:5]

array([[13, 14],
       [18, 19]])

In [87]:
ar > 5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [88]:
ar[ar > 5]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
short_arr = np.array([2,3,4])

In [95]:
short_arr[[False,  True,  True]]

array([3, 4])

In [105]:
a1 = np.arange(5)
a2 = np.arange(3,8)

In [110]:
print(a1)
print(a2)
print(a1 + a2)

[0 1 2 3 4]
[3 4 5 6 7]
[ 3  5  7  9 11]


In [112]:
print(a1)
print(a2)
print(a1 * a2)

[0 1 2 3 4]
[3 4 5 6 7]
[ 0  4 10 18 28]


In [113]:
print(a1)
print(a2)
print(a1 ** a2)

[0 1 2 3 4]
[3 4 5 6 7]
[    0     1    32   729 16384]


In [114]:
a1 + 100

array([100, 101, 102, 103, 104])

In [119]:
ar1 = [
    [1,2,3],
    [2,3,4]
]
ar2 = [
    [10,20,30],
    [20,30,40]
]

In [125]:
print(ar1)
print(ar2)
print(ar1 + ar2)
# Different behaviour!!

[[1, 2, 3], [2, 3, 4]]
[[10, 20, 30], [20, 30, 40]]
[[1, 2, 3], [2, 3, 4], [10, 20, 30], [20, 30, 40]]


In [132]:
for i, v in enumerate(ar1): print(np.array(v) + ar2[i])

[11 22 33]
[22 33 44]


In [134]:
a1

array([0, 1, 2, 3, 4])

In [136]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [137]:
np.exp(a1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [138]:
np.max(a1)  # Same as a1.max()

4

In [139]:
np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [140]:
np.cos(a1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [141]:
np.log(a1)

<ipython-input-141-f50b4f369011>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [142]:
# Docs: https://numpy.org/doc/stable/reference/ufuncs.html